language: swift
osx_image: xcode10.1
xcode_project: ios-app.xcodeproj
xcode_scheme: Testpress.in
xcode_sdk: iphonesimulator12.1
before_install:
- curl -L -O https://github.com/Carthage/Carthage/releases/download/0.31.2/Carthage.pkg
- sudo installer -pkg Carthage.pkg -target /
- curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
- sudo installer -pkg CartfileDiff.pkg -target /
- gem install fastlane --no-ri --no-rdoc --no-document
cache:
  directories:
  - Carthage
install: true
script:
- script/bootstrap
- fastlane scan -s Testpress.in
os: osx
env:
  global:
    secure: QuYZtAqVJYmufSHDw61IzdnB4C4aD18ZKziRsR672L5KkTooZg3pZl+shzVHFYXn/KJsZoH6rRy2QvqwOkE/TMpoO0updlGOye0b76ol8bfgTYPlf+7ahR25M+Avdwpe7kpwT4ErJH4i6K8NyxJxEu7OSSiyPAP0LZFSM2AYPKlec2+jdVr4Iz2imkM1hHRPX2tsCJR8HSf9NvEuLx2XimJlLAblWcUPlVoeFdv6p7q3OpwEiIKYbUjT/N+mRDOcumzoDpKp6KZzGJJbAzM5i34uPpIO35OH1GZ32whudKd0eRrchqXoi1G4zvD/y0+AR+NptIkDBaB5CWZ5YesanFDKxOSP0yhqGLCznA73rpFy9hZOY4+zNSEPrdlj3Rmrwrck/syDDiXwy0atvPyFRiFL04uTgj06SrjzFvhFbBaG9ZYLBuSQLFK4qywShE3xj5c68uX0bQTh66r8yVFbB3Rh8Mdjp+z5bRIgY33WHp3rYyTCWzniTaMbmZ7F5c8rDnWiSK4KvXP2tHdn7lqzXKDeNlefBFI/jIollvr5rUAGuhew0nZda2lfHOBAw5nkJMzI8o74rQveRj4xx0AuGNPstc8OUxVhs2x3klgi8LJ5UKlBLDYuf2H8k2/AaBbsVzhXn1TvMFs4AyAGqDi7DD9xitqcgNoVxuBdfxSANSk=
