language: swift
osx_image: xcode10.1
xcode_project: ios-app.xcodeproj
xcode_scheme: Testpress.in
xcode_sdk: iphonesimulator12.1
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.31.2/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  - gem install fastlane --no-ri --no-rdoc --no-document
cache:
  directories:
    - Carthage
install: true
script:
  - script/cache-carthage
  - fastlane scan -s Testpress.in
os: osx